'''
What causes a unit test to fail?


In the test result report, the character ., as shown below, stands for a passing test. A passing test is good news as it means that your function works as expected. The character F stands for a failing test. A failing test is bad news as this means that something is broken.

    test_row_to_list.py .F.                                                  [100%]

Which of the following describes best why a unit test fails?

Answer the question
50XP

Possible Answers : 

    - The assert statement passes.

    - The assert statement cannot be run because an exception is raised while running the unit test code.

    - The assert statement raises an AssertionError.

    - An exception is raised when running the unit test. This could be an AssertionError raised by the assert statement or another exception, e.g. NameError, which is raised before the assert statement can run.

Answer : An exception is raised when running the unit test. This could be an AssertionError raised by the assert statement or another exception, e.g. NameError, which is raised before the assert statement can run.

'''
